POST http://localhost:3000/api/contato
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YzUwZTAwYTU5NmYxMjdhM2UwYTI2OCIsImlhdCI6MTcwNzQyMDY1NCwiZXhwIjoxNzEwMDEyNjU0fQ.nM5AtPcpmNCObwk7TMKEnGuUwgxuPaFOZ7L1pF8TRmo

{
    "name": "lucas",
    "email": "gabrieltjkhjkeste3@gmail.com",
    "telefone": "1234568",
    "image": "https://love.doghero.com.br/wp-content/uploads/2018/12/golden-retriever-1.png"
}

### bucas todos os contatos do usuário

GET http://localhost:3000/api/contatos/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YzUwZTAwYTU5NmYxMjdhM2UwYTI2OCIsImlhdCI6MTcwNzQyMDY1NCwiZXhwIjoxNzEwMDEyNjU0fQ.nM5AtPcpmNCObwk7TMKEnGuUwgxuPaFOZ7L1pF8TRmo


### busca contato específico
GET http://localhost:3000/api/contato?name=lucasn
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YzUwZTAwYTU5NmYxMjdhM2UwYTI2OCIsImlhdCI6MTcwNzQyMDY1NCwiZXhwIjoxNzEwMDEyNjU0fQ.nM5AtPcpmNCObwk7TMKEnGuUwgxuPaFOZ7L1pF8TRmo



### delete contato
DELETE http://localhost:3000/api/contato/65c5455234a8746cc370748a
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YzUwZTAwYTU5NmYxMjdhM2UwYTI2OCIsImlhdCI6MTcwNzQyMDY1NCwiZXhwIjoxNzEwMDEyNjU0fQ.nM5AtPcpmNCObwk7TMKEnGuUwgxuPaFOZ7L1pF8TRmo

### 
PUT http://localhost:3000/api/contato/65c167587bb9928afba06232
Content-Type: application/json

{
    "name": "gabriel 5 editado",
    "email": "gabrielteste3@gmail.com",
    "telefone": "1234568",
    "image": "https://love.doghero.com.br/wp-content/uploads/2018/12/golden-retriever-1.png"
}

###
POST http://localhost:3000/api/cadastrar
Content-Type: application/json

{
    "name": "jacan",
    "email": "jacano@gmail.com",
    "password": "123456"
}

### login
POST http://localhost:3000/api/login
Content-Type: application/json 

{
   "email": "gabrieltjkhjkeste3@gmail.com",
    "password": "123456"
}

### contatos usuário autenticado
GET http://localhost:3000/api/contato
Authorization:  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YzNhOTNlMGZlNmMxZGEwOTMyMjNmMSIsImlhdCI6MTcwNzMyMjIwNiwiZXhwIjoxNzA5OTE0MjA2fQ.nvhgaAU3xtbaUONRsPPIylGPY7N-MT3Dtx9ZDpXKsH0"

### cadastro com token
POST http://localhost:3000/api/contato
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YzNhOTNlMGZlNmMxZGEwOTMyMjNmMSIsImlhdCI6MTcwNzMyMzUwMywiZXhwIjoxNzA5OTE1NTAzfQ.sicnG-W7pxFZPkjiAGaQISdqc43QsZJ5Nq-TLlFh8HM

{
    "name": "contato do carlos",
    "email": "email@gmail.com",
    "telefone": "123456789",
    "image": "https://example.com/imagem_do_contato.jpg",
    "user": "65c3a93e0fe6c1da093223f1"
}

### delete usuário

DELETE http://localhost:3000/api/usuario/delete
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YzUwM2Q1ZTAwMTZmNjg5Y2VlMDU5ZCIsImlhdCI6MTcwNzQxMDM5OCwiZXhwIjoxNzEwMDAyMzk4fQ.YsyyveL3ZU_FPDaTmQHZ6fHueqyoWYy2i4qhGetnkXs

### atualizar usuário
PUT http://localhost:3000/api/usuario/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YzUwZTAwYTU5NmYxMjdhM2UwYTI2OCIsImlhdCI6MTcwNzQyMDY1NCwiZXhwIjoxNzEwMDEyNjU0fQ.nM5AtPcpmNCObwk7TMKEnGuUwgxuPaFOZ7L1pF8TRmo

{
    "name": "jacaN EDIT",
    "email": "janemail@gmail.com"
}